### ISSUE TITLE
Setup GitHub projects button diesn't work

### ISSUE THREAD

**Issue by simonachmueller** [EnixCoda/github-code-review-notifier#13]
Ho to reproduce:

1. Install github-code-review-notifier in Slack
2. Click on "Setup GitHub projects": it works (at least 2 months ago)
3. Setup all and work with the App - awesome
4. After 2 months click on "Setup GitHub projects" again: it opens a link in browser like https://github-code-review-notifier.now.sh/github?workspace=XXXXXXX, but the response have code 400 and message "Error: no github event header provided"

**Comment by simonachmueller** [comment]
Ah ok, now when playing around with the App I received a message from the App "Please setup your GitHub projects with this webhook:", and now I got the idea that it's just a webhook to setup in the github, not the settings page. 

I'm not really sure why the button was working like opening this link in the browser before...

**Comment by EnixCoda** [comment]
Interesting, looks like an issue of Slack and has been fixed?

**Comment by simonachmueller** [comment]
Yeah, it seems like an issue of Slack, I will close this issue as not reproducible.
