### ISSUE TITLE
Is there a way to get on slack only my code review requests?

### ISSUE THREAD

**Issue by nitaiaharoni1** [EnixCoda/github-code-review-notifier#14]
When linking the "Code Review Notifier" slack app to a webhook and adding more people the channel, It notifies on each and everyone's code review requests.

is it possible to get just my code review requests?

**Comment by EnixCoda** [comment]
You should DM "Code Review Notifier" to setup (like shown below) instead of inviting it to channels.

![image](https://user-images.githubusercontent.com/7480839/80105247-df915680-85aa-11ea-9183-bfd3f74e33d9.png)

**Comment by EnixCoda** [comment]
Updated readme to prevent such misunderstandings.

![image](https://user-images.githubusercontent.com/7480839/80105540-52023680-85ab-11ea-853c-7fa6c1ab633d.png)

**Comment by nitaiaharoni1** [comment]
I did DM, and this way linked my team members to the channel/bot, but then on every code review request (for everyone in the team), the slack bot notifies.

Is there a way it will only notify the one who was requested to review?
