### ISSUE TITLE
Error: no github event header provided

### ISSUE THREAD

**Issue by scottamplitude** [EnixCoda/github-code-review-notifier#19]
Clicking on Setup GitHub projects triggers a message in Slack:
Please setup your GitHub projects with this webhook:
with a link, like: https://github-code-review-notifier.now.sh/github?workspace=#########
When clicking that link I'm taken to a page that says:

![image](https://user-images.githubusercontent.com/77700297/113945136-91c12e80-97ba-11eb-82a8-fb4adf0d2fd4.png)

**Comment by EnixCoda** [comment]
Hi @scottamplitude 

This link is not supposed to be accessed through browser. Please add this link to your repository's webhooks.

You can visit `https://github.com/{username}/{repository}/settings/hooks` to setup webhooks.

**Comment by scottamplitude** [comment]
Oh, my fault!  Thanks for the GitHub webhooks 101 tutorial.  :)
